name: mmoInfoCoords
main: mmo.Info.MMOInfoCoords
version: 1.0
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [mmoCore,mmoInfo]

description: Adds {coords} to the info tokens
permissions:
  mmo.info.coords:
    description: Allows {coords} to show the current player coordinates
    default: op
